# Generated by Django 3.2 on 2021-04-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='nft_uploads/')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
        ),
    ]
