# Generated by Django 3.2 on 2021-04-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='nft',
            name='image',
            field=models.ImageField(null=True, upload_to='nft_uploads/'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
