# Generated by Django 3.2 on 2021-04-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
