# Generated by Django 3.2 on 2021-05-02 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nft', '0004_alter_nft_publishedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='uploaded_by',
            field=models.ForeignKey(db_column='username', default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
