# Generated by Django 3.2 on 2021-05-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0005_nft_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='quantity',
            field=models.IntegerField(default='5'),
        ),
    ]
